config/routes.rb
Rails.application.routes.draw do
  resources :lesson_plans

  resources :homeworks

  resources :resources

  resources  :events
  resources  :inqueries
  resources  :students
  resources  :teachers
  resources  :groups
  resources  :photos
  devise_for :users

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  authenticated :user do
    root 'pages#home', as: "authenticated_root"
  end
  root 'welcome#index'

  get  "about" => "pages#about"
  get  "calendar" => "pages#calendar"

scope '(:locale)' do resources :orders
  resources :events
  root 'pages#home', as: 'home', via: :all
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

	belongs_to :group
	belongs_to :teacher
	has_many :students
end

app/models/group.rb
class Group < ActiveRecord::Base
	validates :name, uniqueness: true

	belongs_to :teacher
	has_many :students
	has_many :homeworks
	has_many :events
end

app/models/homework.rb
class Homework < ActiveRecord::Base
	validates :group, presence: true

	belongs_to :group
end

app/models/inquery.rb
class Inquery < ActiveRecord::Base
end

app/models/lesson_plan.rb
class LessonPlan < ActiveRecord::Base
	belongs_to :user
	
has_attached_file :image
validates_attachment_presence :image
validates_attachment_content_type :image, :content_type => [ 'application/pdf','text/plain']
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	validates :description, presence: true
  
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "600x600>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/resource.rb
class Resource < ActiveRecord::Base

belongs_to :user

end

app/models/student.rb
class Student < ActiveRecord::Base
   has_many :teachers, through: :groups
   belongs_to :group
   belongs_to :user
   
   belongs_to :events

   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "150x150>" }
	 validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	validates :ename, presence: true
	validates :cname, presence: true
	validates :dob, presence: true

	has_many :students, through: :groups
	has_many :groups
	has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
  has_many :lesson_plans
  has_many :resources
  has_one  :student
  acts_as_messageable

  def mail_email(object)
    email
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  respond_to :html

  def index
    @groups = Group.all
    respond_with(@groups)
  end

  def show
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.save
    respond_with(@group)
  end

  def update
    @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :teacher_id, :pa, :school)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_header(text)
    content_for(:page_header) { text.to_s }
  end

  def gravatar_for(user, size = 30, title = user.name)
    image_tag gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/inqueries_helper.rb
module InqueriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}' data-img-src='#{gravatar_image_url(user.email, size: 50)}'>#{user.name}</option>"
    end
    s.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% @group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t('.lead') %><br>
    <%= f.collection_select(:teacher_id, Teacher.all, :id, :ename, prompt: true) %>
  </div>

  <div class="form-group">
    <%= f.label t('.pa') %><br>
    <%= f.collection_select(:pa, Teacher.all, :ename, :ename, prompt: true) %>
  </div>

  <div class="form-group">
    <%= f.label t('.curriculum') %><br>
    <%= f.select :school, ["English","Drum","English & Drum"] %>
  </div>

  <div class="form-group">
    <%= f.label t('.classname') %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<% page_header t('.edit') %>
<div class="box">

<%= render 'form' %>

<%= link_to t('.show'), @group %> |
<%= link_to t('.back'), groups_path %>
</div>

app/views/groups/index.html.erb
<div class="box">
<% page_header t('.header') %>

    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th><%= t('.classname') %>:</th>
          <th><%= t('.curriculum') %>:</th>
          <% if current_user.admin? %>
            <th><%= t('.numberstudents') %>:</th>
            <th><%= t('.scheduledclasses') %>:</th>
          <% end %>
          <th><%= t('.leadteacher') %>:</th>
          <th><%= t('.pa') %>:</th>
            <% if current_user.admin? %>
              <th colspan="2">Admin Options</th>
            <% end %>
        </tr>
      </thead>

      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td><%= link_to group.name, group %></td>
            <td><%= group.school %></td>
            <% if current_user.admin? %>
              <td><%= group.students.count %></td>
              <td><%= group.events.count %></td>
            <% end %>
            <td><%= group.teacher.ename %></td>
            <td><%= group.pa %></td>
            <% if current_user.admin? %>
              <td>
                <%= link_to edit_group_path(group) do %>
                <i class="fa fa-pencil-square-o"></i>
                <% end %>
              </td>
              <td>
                <%= link_to group, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fa fa-trash-o"></i>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br />

    <p><%= t('.currently') %><strong><%= @groups.count %> Classes</strong></p>

    <br />
        <%= link_to 'Add New Class', new_group_path, class: "btn btn-primary"  %>
    <%= link_to 'Scheduled Classes', events_path, class: "btn btn-default"  %>
  </div>

app/views/groups/new.html.erb
<div class="box">
	<% page_header "Add a new class" %>
	<li><%= t('.bullet1') %>
	<li><%= t('.bullet2') %>
	<li><%= t('.bullet3') %>
	<br />
	<br />
	<%= render 'form' %>

	<%= link_to 'Back', groups_path %>
</div>

app/views/groups/show.html.erb
<% page_header t('.header') %>

<div class="box">

		<h2>
			<center>
					  <%= @group.name %>
			</center>
		</h2>

<br />

		<p>
			<strong><%= t('.lead') %></strong>
				<%= link_to @group.teacher.ename, @group.teacher %>
		</p>

		<p>
		  <strong><%= t('.pa') %></strong>
		  <%= @group.pa %>
		</p>

		<p>
		  <strong><%= t('.type') %></strong>
		  <%= @group.school %>
		</p>

		<p>
		  <strong><%= @group.students.count %> Students:</strong>
		  	<ol>
					<% @group.students.each do |student| %>
					  <li><%= link_to student.ename, student %> - <%= student.cname %> - <%= student.dob %></li>
					<% end %>
				</ol>
		</p>

		<br>

				<p>
		  <strong><%= @group.events.count %> Class Periods:</strong>
		  	<ol>
					<% @group.events.each do |event| %>
					  <li><%= link_to event.start_time, event %> - <%= event.teacher.ename %> - <%= event.ta %></li>
					<% end %>
				</ol>
		</p>
		<br />

		<%= link_to 'All Classes', groups_path, class: "btn btn-primary" %>
		<%= link_to 'New event', new_event_path, class: "btn btn-default" %>
		<%= link_to 'Edit Class', edit_group_path(@group), class: "btn btn-default"  %>


</div>