config/routes.rb
Rails.application.routes.draw do
  resources :lesson_plans

  resources :homeworks

  resources :resources

  resources  :events
  resources  :inqueries
  resources  :students
  resources  :teachers
  resources  :groups
  resources  :photos
  devise_for :users

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  authenticated :user do
    root 'pages#home', as: "authenticated_root"
  end
  root 'welcome#index'

  get  "about" => "pages#about"
  get  "calendar" => "pages#calendar"

scope '(:locale)' do resources :orders
  resources :events
  root 'pages#home', as: 'home', via: :all
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

	belongs_to :group
	belongs_to :teacher
	has_many :students
end

app/models/group.rb
class Group < ActiveRecord::Base
	validates :name, uniqueness: true

	belongs_to :teacher
	has_many :students
	has_many :homeworks
	has_many :events
end

app/models/homework.rb
class Homework < ActiveRecord::Base
	validates :group, presence: true

	belongs_to :group
end

app/models/inquery.rb
class Inquery < ActiveRecord::Base
end

app/models/lesson_plan.rb
class LessonPlan < ActiveRecord::Base
	belongs_to :user
	
has_attached_file :image
validates_attachment_presence :image
validates_attachment_content_type :image, :content_type => [ 'application/pdf','text/plain']
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	validates :description, presence: true
  
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "600x600>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/resource.rb
class Resource < ActiveRecord::Base

belongs_to :user

end

app/models/student.rb
class Student < ActiveRecord::Base
   has_many :teachers, through: :groups
   belongs_to :group
   belongs_to :user
   
   belongs_to :events

   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "150x150>" }
	 validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	validates :ename, presence: true
	validates :cname, presence: true
	validates :dob, presence: true

	has_many :students, through: :groups
	has_many :groups
	has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
  has_many :lesson_plans
  has_many :resources
  has_one  :student
  acts_as_messageable

  def mail_email(object)
    email
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :verify_is_admin, only: [:show, :edit, :update, :destroy]
  
  respond_to :html

  def index
    @teachers = Teacher.paginate(:page => params[:page], :per_page => 10)
    respond_with(@teachers)
  end

  def show
    respond_with(@teacher)
  end

  def new
    @teacher = Teacher.new
    respond_with(@teacher)
  end

  def edit
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.save
    respond_with(@teacher)
  end

  def update
    @teacher = Teacher.find(params[:id])
    respond_with(@teacher)
  end

  def destroy
    @teacher.destroy
    respond_with(@teacher)
  end

  private
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    def teacher_params
      params.require(:teacher).permit(:ename, :cname, :dob, :group_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_header(text)
    content_for(:page_header) { text.to_s }
  end

  def gravatar_for(user, size = 30, title = user.name)
    image_tag gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/inqueries_helper.rb
module InqueriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}' data-img-src='#{gravatar_image_url(user.email, size: 50)}'>#{user.name}</option>"
    end
    s.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('.ename') %><br>
    <%= f.text_field :ename, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label t('.cname') %><br>
    <%= f.text_field :cname, class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label t('.dob') %><br>
    <%= f.date_select :dob %>
  </div>

<br />

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', teachers_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<% page_header t('.header') %>
<div class="box">

<h2>
	<center>
		<%= link_to @teacher.ename %>
	</center>
</h2>
<br />

<%= render 'form' %>

</div>

app/views/teachers/index.html.erb
<div class="box">
<% page_header t('.header') %>

    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>English Name</th>
          <th>Chinese Name</th>
          <th>Date of Birth</th>
            <% if current_user.admin? %>
              <th colspan="3">Admin Options</th>
            <% end %>
        </tr>
      </thead>

      <%= will_paginate @students %>

      <tbody>
        <% @teachers.each do |teacher| %>
          <tr>
            <td><%= link_to teacher.ename, teacher %></td>
            <td><%= link_to teacher.cname, teacher %></td>
            <td><%= teacher.dob %></td>
            <% if current_user.admin? %>
              <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
              <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @students %>

    <br />
    <%= link_to 'New Teacher', new_teacher_path, class: "btn btn-primary" %>
</div>

app/views/teachers/new.html.erb
<% page_header t('.header') %>
<div class="box">
	<li>
		Fill out the form below to add a new person to Balern faculty/staff.
	</li>
	<li>
		If the new faculty member is a teacher, then classes can be added via
		the <%= link_to "Classes", groups_path %> form.
	</li>
	<br />
<%= render 'form' %>

</div>

app/views/teachers/show.html.erb
<% page_header @teacher.ename %>
<p id="notice"><%= notice %></p>



<div class="box col-xs-5">
	<p>
	  <strong><%= @teacher.cname %>'s Class Schedule:</strong>
	  	<ol>
			<% @teacher.groups.each do |group| %>
			  <li><%= link_to group.name, group %></li>
			<% end %>
		</ol>
	</p>

	<br />
	<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
	<%= link_to 'Back', teachers_path %>
	<br />
	
</div>

<div class="col-xs-1"></div>

<div class="box col-xs-6">
	<center>
		<h2>
			<%= @teacher.cname %>
		</h2>
	</center>

	<p>
	  <strong>Dob:</strong>
	  <%= @teacher.dob %>
	</p>

	<p>
	  <strong>Contact Number:</strong>
	  <%= @teacher.phone %>
	</p>

	<p>
	  <strong>email:</strong>
	  <%= @teacher.email %>
	</p>

	<p>
	  <strong>Time with Balern:</strong>
	  <%= @teacher.duration %>
	</p>
</div>