config/routes.rb
Rails.application.routes.draw do
  resources :lesson_plans

  resources :homeworks

  resources :resources

  resources  :events
  resources  :inqueries
  resources  :students
  resources  :teachers
  resources  :groups
  resources  :photos
  devise_for :users

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  authenticated :user do
    root 'pages#home', as: "authenticated_root"
  end
  root 'welcome#index'

  get  "about" => "pages#about"
  get  "calendar" => "pages#calendar"

scope '(:locale)' do resources :orders
  resources :events
  root 'pages#home', as: 'home', via: :all
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

	belongs_to :group
	belongs_to :teacher
	has_many :students
end

app/models/group.rb
class Group < ActiveRecord::Base
	validates :name, uniqueness: true

	belongs_to :teacher
	has_many :students
	has_many :homeworks
	has_many :events
end

app/models/homework.rb
class Homework < ActiveRecord::Base
	validates :group, presence: true

	belongs_to :group
end

app/models/inquery.rb
class Inquery < ActiveRecord::Base
end

app/models/lesson_plan.rb
class LessonPlan < ActiveRecord::Base
	belongs_to :user
	
has_attached_file :image
validates_attachment_presence :image
validates_attachment_content_type :image, :content_type => [ 'application/pdf','text/plain']
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	validates :description, presence: true
  
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "600x600>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/resource.rb
class Resource < ActiveRecord::Base

belongs_to :user

end

app/models/student.rb
class Student < ActiveRecord::Base
   has_many :teachers, through: :groups
   belongs_to :group
   belongs_to :user
   
   belongs_to :events

   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "150x150>" }
	 validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	validates :ename, presence: true
	validates :cname, presence: true
	validates :dob, presence: true

	has_many :students, through: :groups
	has_many :groups
	has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
  has_many :lesson_plans
  has_many :resources
  has_one  :student
  acts_as_messageable

  def mail_email(object)
    email
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/inqueries_helper.rb
module InqueriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}' data-img-src='#{gravatar_image_url(user.email, size: 50)}'>#{user.name}</option>"
    end
    s.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :focus %><br>
    <%= f.text_field :focus %>
  </div>
    <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="form-group">
    <%= f.label :level %><br>
    <%= f.select :level, options_for_select(%w[purple_parrots Green_Monkeys Silver_snakes VIP]) %>
  </div>

<br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br />

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<% page_header t('.head') %>

<body>
  <div class="container">
    <div class="jumbotron">
        <p><%= t('.bookint') %></p>
        <p><%= link_to t('.learnmore'), new_inquery_path, class: "btn btn-primary btn-lg" %> 
        </p>
      </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag 'mouse1.jpg', :class => "img-circle" %>
      <div class="caption">
        <h3>ABC Mouse</h3>
        <p><%= t('.abc') %></p>
        <p>
          <%= link_to t('.button1'), "https://www.abcmouse.com/", class: "btn btn-primary" %>
          <%= link_to t('.button2'), new_inquery_path, class: "btn btn-default" %>
        </p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag 'ce.png', :class => "img-circle" %>
      <div class="caption">
        <h3>The Cutting Edge</h3>
        <p><%= t('.ce') %></p>
        <p>
          <%= link_to t('.button1'), "http://www.pearsonlongman.com/newcuttingedge/", class: "btn btn-primary" %>
          <%= link_to t('.button2'), new_inquery_path, class: "btn btn-default" %>
        </p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag 'lg.png', :class => "img-circle" %>
      <div class="caption">
        <h3>Let's Go!</h3>
        <p><%= t('.lg') %></p>
        <p>
          <%= link_to t('.button1'), "https://elt.oup.com/student/letsgo/?cc=global&selLanguage=en", class: "btn btn-primary" %>
          <%= link_to t('.button2'), new_inquery_path, class: "btn btn-default" %>
        </p>
      </div>
    </div>
  </div>
</div>
<br />
<%= link_to 'New Resource', new_resource_path, class: "btn btn-primary" %>
<br />
<br />
<div id="photos" class="transitions-enabled">
  <% @resources.each do |resource| %>
    <div class="bot panel panel-default">
      <%= link_to (resource.title), resource.url %>
      <div class="panel-body">
        <%= resource.notes %>
        level: 
        <strong>
          <%= resource.level %>
        </strong>
        <br />
        Reccomended by:  
        <strong>
          <%= resource.user.name if resource.user %>
        </strong>

        <% if resource.user == current_user %>
          <%= link_to 'Edit', edit_resource_path(resource) %>
          <%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>
<br />
<br />

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Site:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Focus:</strong>
  <%= @resource.focus %>
</p>

<p>
  <strong>Url:</strong>
  <%= @resource.url %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>